### ISSUE TITLE
Crystal Ball can't load sleeper user leagues

### ISSUE THREAD

**Issue by joeflan** [dynastyprocess/apps#16]
Getting the following error when trying to load a league:

"Couldn't load leagues for Sleeper user x. Error code: Error: Column `name` not found in `.data`"

![image](https://user-images.githubusercontent.com/15068380/133634712-e236a1bf-f3c5-48f7-8635-4543f9a4a68e.png)

Have tried a couple of different users all with the same issue.

**Comment by tanho63** [comment]
Lmao I guess I got busted for hardcoding here https://github.com/dynastyprocess/apps/blob/13241945b4cf7505b1d5429dcf64b87b2a72ffa2/crystal-ball/functions.R#L185

**Comment by tanho63** [comment]
I probably won't get to a crystal ball release til next week given the way my week/weekend is shaping up

**Comment by joeflan** [comment]
Yeah I was doing some troubleshooting and figured it was the hardcoded year because I checked with one of your test users and it worked. No worries on how quickly we can get to it. Are you thinking of just updating the year or adding a "league year" picker function?

**Comment by tanho63** [comment]
crystal ball only makes sense for the current year once one or two games have been played, I’ll probably write handling so that it only rolls over in September etc

**Comment by tanho63** [comment]
I think this got resolved.
